name: Deploy Laravel App

on:
  push:
    branches:
      - beta  # Deploy beta on each commit
  release:
    types:
      - published  # Deploy production on release

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your local machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old containers
        run: docker compose down

      - name: Pull latest image & rebuild
        run: |
          docker compose pull
          docker compose up -d --build

      - name: Install Composer Dependencies
        run: docker exec laravel_app composer install --no-dev --optimize-autoloader

      - name: Fix Permissions
        run: |
          docker exec laravel_app chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
          docker exec laravel_app chmod -R 775 /var/www/storage /var/www/bootstrap/cache

      - name: Run Migrations
        run: docker exec laravel_app php artisan migrate --force

