name: Deploy Laravel App

on:
  push:
    branches:
      - beta  # Deploy beta on each commit
  release:
    types:
      - published  # Deploy production on release

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your local machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old containers
        run: docker compose down

      - name: Pull latest image & rebuild
        run: |
          docker compose pull
          docker compose up -d --build

      - name: Run Migrations
        run: docker compose exec -T app php artisan migrate --force
